# This file can be used for thesting the API with a dedicated Visual Studio Code extension.

## Execute Register
POST http://localhost:3001/api/register HTTP/1.1
content-type: application/json

{
    "username": "@gmail.com",
    "password": "abc",
    "role": "admin"
}
### 

## Execute Login
POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "admin",
    "role": "admin"
}
### 

## Execute Logout
POST http://localhost:3001/api/logout HTTP/1.1
content-type: application/json

{
    
}
### 

## get role.
GET http://localhost:3001/api/8/getRole HTTP/1.1

###

## get phase.
GET http://localhost:3001/api/getPhase HTTP/1.1

###


## Execute Phase change
POST http://localhost:3001/api/changePhase HTTP/1.1
content-type: application/json

{
    "current_phase": 2
    
}
### 

## Execute set Budget
POST http://localhost:3001/api/setBudget HTTP/1.1
content-type: application/json

{
    "budget": 100
    
}
### 

## get budget.
GET http://localhost:3001/api/getBudget HTTP/1.1

###


## Execute add Proposal
POST http://localhost:3001/api/addProposal HTTP/1.1
content-type: application/json

{
    "user_id": 39,
    "description":"aaaa",
    "cost": 50
    
}
### 


## Execute delete Proposal
POST http://localhost:3001/api/deleteProposal HTTP/1.1
content-type: application/json

{
   "cost":500,
   "description": "abc"
    
}
### 

## get proposal.
GET http://localhost:3001/api/getProposal/34 HTTP/1.1

###


## Execute user by user_id
POST http://localhost:3001/api/getUser HTTP/1.1
content-type: application/json

{
   "user_id": 29
    
}
### 


## Execute update score
POST http://localhost:3001/api/updateScore HTTP/1.1
content-type: application/json

{
   "user_id": 2,
   "proposal_id": 1,
   "score": "2"
    
}
###


## Execute final Proposals
POST http://localhost:3001/api/finalProposals HTTP/1.1
content-type: application/json

{
   
    
}
###


## Execute reset votes and proposals
POST http://localhost:3001/api/resetDb HTTP/1.1
content-type: application/json

{
   
    
}
###

